// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: warehouse/warehouse.proto

package warehouse

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WarehouseService_ListLocations_FullMethodName        = "/erposfnb.warehouse.WarehouseService/ListLocations"
	WarehouseService_CreateLocation_FullMethodName       = "/erposfnb.warehouse.WarehouseService/CreateLocation"
	WarehouseService_ListSuppliers_FullMethodName        = "/erposfnb.warehouse.WarehouseService/ListSuppliers"
	WarehouseService_CreateSupplier_FullMethodName       = "/erposfnb.warehouse.WarehouseService/CreateSupplier"
	WarehouseService_CreatePurchaseOrder_FullMethodName  = "/erposfnb.warehouse.WarehouseService/CreatePurchaseOrder"
	WarehouseService_CreateGoodsReceipt_FullMethodName   = "/erposfnb.warehouse.WarehouseService/CreateGoodsReceipt"
	WarehouseService_CreateTransfer_FullMethodName       = "/erposfnb.warehouse.WarehouseService/CreateTransfer"
	WarehouseService_CreateAdjustment_FullMethodName     = "/erposfnb.warehouse.WarehouseService/CreateAdjustment"
	WarehouseService_CreateStockOpname_FullMethodName    = "/erposfnb.warehouse.WarehouseService/CreateStockOpname"
	WarehouseService_ListStockOpnames_FullMethodName     = "/erposfnb.warehouse.WarehouseService/ListStockOpnames"
	WarehouseService_GetStockOpname_FullMethodName       = "/erposfnb.warehouse.WarehouseService/GetStockOpname"
	WarehouseService_ListStockRequests_FullMethodName    = "/erposfnb.warehouse.WarehouseService/ListStockRequests"
	WarehouseService_RequestStock_FullMethodName         = "/erposfnb.warehouse.WarehouseService/RequestStock"
	WarehouseService_ApproveStockRequest_FullMethodName  = "/erposfnb.warehouse.WarehouseService/ApproveStockRequest"
	WarehouseService_RejectStockRequest_FullMethodName   = "/erposfnb.warehouse.WarehouseService/RejectStockRequest"
	WarehouseService_ShipStockRequest_FullMethodName     = "/erposfnb.warehouse.WarehouseService/ShipStockRequest"
	WarehouseService_StockRequestReceived_FullMethodName = "/erposfnb.warehouse.WarehouseService/StockRequestReceived"
)

// WarehouseServiceClient is the client API for WarehouseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WarehouseService serves location, supplier, purchase order, stock, opname,
// and stock request work. It is a private core service.
type WarehouseServiceClient interface {
	ListLocations(ctx context.Context, in *ListLocationsRequest, opts ...grpc.CallOption) (*ListLocationsResponse, error)
	CreateLocation(ctx context.Context, in *CreateLocationRequest, opts ...grpc.CallOption) (*CreateLocationResponse, error)
	ListSuppliers(ctx context.Context, in *ListSuppliersRequest, opts ...grpc.CallOption) (*ListSuppliersResponse, error)
	CreateSupplier(ctx context.Context, in *CreateSupplierRequest, opts ...grpc.CallOption) (*CreateSupplierResponse, error)
	CreatePurchaseOrder(ctx context.Context, in *CreatePurchaseOrderRequest, opts ...grpc.CallOption) (*CreatePurchaseOrderResponse, error)
	CreateGoodsReceipt(ctx context.Context, in *CreateGoodsReceiptRequest, opts ...grpc.CallOption) (*CreateGoodsReceiptResponse, error)
	CreateTransfer(ctx context.Context, in *CreateTransferRequest, opts ...grpc.CallOption) (*CreateTransferResponse, error)
	CreateAdjustment(ctx context.Context, in *CreateAdjustmentRequest, opts ...grpc.CallOption) (*CreateAdjustmentResponse, error)
	CreateStockOpname(ctx context.Context, in *CreateStockOpnameRequest, opts ...grpc.CallOption) (*CreateStockOpnameResponse, error)
	ListStockOpnames(ctx context.Context, in *ListStockOpnamesRequest, opts ...grpc.CallOption) (*ListStockOpnamesResponse, error)
	GetStockOpname(ctx context.Context, in *GetStockOpnameRequest, opts ...grpc.CallOption) (*GetStockOpnameResponse, error)
	ListStockRequests(ctx context.Context, in *ListStockRequestsRequest, opts ...grpc.CallOption) (*ListStockRequestsResponse, error)
	RequestStock(ctx context.Context, in *RequestStockRequest, opts ...grpc.CallOption) (*RequestStockResponse, error)
	ApproveStockRequest(ctx context.Context, in *ApproveStockRequestRequest, opts ...grpc.CallOption) (*ApproveStockRequestResponse, error)
	RejectStockRequest(ctx context.Context, in *RejectStockRequestRequest, opts ...grpc.CallOption) (*RejectStockRequestResponse, error)
	ShipStockRequest(ctx context.Context, in *ShipStockRequestRequest, opts ...grpc.CallOption) (*ShipStockRequestResponse, error)
	StockRequestReceived(ctx context.Context, in *StockRequestReceivedRequest, opts ...grpc.CallOption) (*StockRequestReceivedResponse, error)
}

type warehouseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWarehouseServiceClient(cc grpc.ClientConnInterface) WarehouseServiceClient {
	return &warehouseServiceClient{cc}
}

func (c *warehouseServiceClient) ListLocations(ctx context.Context, in *ListLocationsRequest, opts ...grpc.CallOption) (*ListLocationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLocationsResponse)
	err := c.cc.Invoke(ctx, WarehouseService_ListLocations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) CreateLocation(ctx context.Context, in *CreateLocationRequest, opts ...grpc.CallOption) (*CreateLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLocationResponse)
	err := c.cc.Invoke(ctx, WarehouseService_CreateLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) ListSuppliers(ctx context.Context, in *ListSuppliersRequest, opts ...grpc.CallOption) (*ListSuppliersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSuppliersResponse)
	err := c.cc.Invoke(ctx, WarehouseService_ListSuppliers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) CreateSupplier(ctx context.Context, in *CreateSupplierRequest, opts ...grpc.CallOption) (*CreateSupplierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSupplierResponse)
	err := c.cc.Invoke(ctx, WarehouseService_CreateSupplier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) CreatePurchaseOrder(ctx context.Context, in *CreatePurchaseOrderRequest, opts ...grpc.CallOption) (*CreatePurchaseOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePurchaseOrderResponse)
	err := c.cc.Invoke(ctx, WarehouseService_CreatePurchaseOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) CreateGoodsReceipt(ctx context.Context, in *CreateGoodsReceiptRequest, opts ...grpc.CallOption) (*CreateGoodsReceiptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGoodsReceiptResponse)
	err := c.cc.Invoke(ctx, WarehouseService_CreateGoodsReceipt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) CreateTransfer(ctx context.Context, in *CreateTransferRequest, opts ...grpc.CallOption) (*CreateTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTransferResponse)
	err := c.cc.Invoke(ctx, WarehouseService_CreateTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) CreateAdjustment(ctx context.Context, in *CreateAdjustmentRequest, opts ...grpc.CallOption) (*CreateAdjustmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAdjustmentResponse)
	err := c.cc.Invoke(ctx, WarehouseService_CreateAdjustment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) CreateStockOpname(ctx context.Context, in *CreateStockOpnameRequest, opts ...grpc.CallOption) (*CreateStockOpnameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateStockOpnameResponse)
	err := c.cc.Invoke(ctx, WarehouseService_CreateStockOpname_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) ListStockOpnames(ctx context.Context, in *ListStockOpnamesRequest, opts ...grpc.CallOption) (*ListStockOpnamesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStockOpnamesResponse)
	err := c.cc.Invoke(ctx, WarehouseService_ListStockOpnames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) GetStockOpname(ctx context.Context, in *GetStockOpnameRequest, opts ...grpc.CallOption) (*GetStockOpnameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStockOpnameResponse)
	err := c.cc.Invoke(ctx, WarehouseService_GetStockOpname_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) ListStockRequests(ctx context.Context, in *ListStockRequestsRequest, opts ...grpc.CallOption) (*ListStockRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStockRequestsResponse)
	err := c.cc.Invoke(ctx, WarehouseService_ListStockRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) RequestStock(ctx context.Context, in *RequestStockRequest, opts ...grpc.CallOption) (*RequestStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestStockResponse)
	err := c.cc.Invoke(ctx, WarehouseService_RequestStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) ApproveStockRequest(ctx context.Context, in *ApproveStockRequestRequest, opts ...grpc.CallOption) (*ApproveStockRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveStockRequestResponse)
	err := c.cc.Invoke(ctx, WarehouseService_ApproveStockRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) RejectStockRequest(ctx context.Context, in *RejectStockRequestRequest, opts ...grpc.CallOption) (*RejectStockRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectStockRequestResponse)
	err := c.cc.Invoke(ctx, WarehouseService_RejectStockRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) ShipStockRequest(ctx context.Context, in *ShipStockRequestRequest, opts ...grpc.CallOption) (*ShipStockRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShipStockRequestResponse)
	err := c.cc.Invoke(ctx, WarehouseService_ShipStockRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *warehouseServiceClient) StockRequestReceived(ctx context.Context, in *StockRequestReceivedRequest, opts ...grpc.CallOption) (*StockRequestReceivedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockRequestReceivedResponse)
	err := c.cc.Invoke(ctx, WarehouseService_StockRequestReceived_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WarehouseServiceServer is the server API for WarehouseService service.
// All implementations must embed UnimplementedWarehouseServiceServer
// for forward compatibility.
//
// WarehouseService serves location, supplier, purchase order, stock, opname,
// and stock request work. It is a private core service.
type WarehouseServiceServer interface {
	ListLocations(context.Context, *ListLocationsRequest) (*ListLocationsResponse, error)
	CreateLocation(context.Context, *CreateLocationRequest) (*CreateLocationResponse, error)
	ListSuppliers(context.Context, *ListSuppliersRequest) (*ListSuppliersResponse, error)
	CreateSupplier(context.Context, *CreateSupplierRequest) (*CreateSupplierResponse, error)
	CreatePurchaseOrder(context.Context, *CreatePurchaseOrderRequest) (*CreatePurchaseOrderResponse, error)
	CreateGoodsReceipt(context.Context, *CreateGoodsReceiptRequest) (*CreateGoodsReceiptResponse, error)
	CreateTransfer(context.Context, *CreateTransferRequest) (*CreateTransferResponse, error)
	CreateAdjustment(context.Context, *CreateAdjustmentRequest) (*CreateAdjustmentResponse, error)
	CreateStockOpname(context.Context, *CreateStockOpnameRequest) (*CreateStockOpnameResponse, error)
	ListStockOpnames(context.Context, *ListStockOpnamesRequest) (*ListStockOpnamesResponse, error)
	GetStockOpname(context.Context, *GetStockOpnameRequest) (*GetStockOpnameResponse, error)
	ListStockRequests(context.Context, *ListStockRequestsRequest) (*ListStockRequestsResponse, error)
	RequestStock(context.Context, *RequestStockRequest) (*RequestStockResponse, error)
	ApproveStockRequest(context.Context, *ApproveStockRequestRequest) (*ApproveStockRequestResponse, error)
	RejectStockRequest(context.Context, *RejectStockRequestRequest) (*RejectStockRequestResponse, error)
	ShipStockRequest(context.Context, *ShipStockRequestRequest) (*ShipStockRequestResponse, error)
	StockRequestReceived(context.Context, *StockRequestReceivedRequest) (*StockRequestReceivedResponse, error)
	mustEmbedUnimplementedWarehouseServiceServer()
}

// UnimplementedWarehouseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWarehouseServiceServer struct{}

func (UnimplementedWarehouseServiceServer) ListLocations(context.Context, *ListLocationsRequest) (*ListLocationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLocations not implemented")
}
func (UnimplementedWarehouseServiceServer) CreateLocation(context.Context, *CreateLocationRequest) (*CreateLocationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLocation not implemented")
}
func (UnimplementedWarehouseServiceServer) ListSuppliers(context.Context, *ListSuppliersRequest) (*ListSuppliersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSuppliers not implemented")
}
func (UnimplementedWarehouseServiceServer) CreateSupplier(context.Context, *CreateSupplierRequest) (*CreateSupplierResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSupplier not implemented")
}
func (UnimplementedWarehouseServiceServer) CreatePurchaseOrder(context.Context, *CreatePurchaseOrderRequest) (*CreatePurchaseOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePurchaseOrder not implemented")
}
func (UnimplementedWarehouseServiceServer) CreateGoodsReceipt(context.Context, *CreateGoodsReceiptRequest) (*CreateGoodsReceiptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGoodsReceipt not implemented")
}
func (UnimplementedWarehouseServiceServer) CreateTransfer(context.Context, *CreateTransferRequest) (*CreateTransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTransfer not implemented")
}
func (UnimplementedWarehouseServiceServer) CreateAdjustment(context.Context, *CreateAdjustmentRequest) (*CreateAdjustmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAdjustment not implemented")
}
func (UnimplementedWarehouseServiceServer) CreateStockOpname(context.Context, *CreateStockOpnameRequest) (*CreateStockOpnameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateStockOpname not implemented")
}
func (UnimplementedWarehouseServiceServer) ListStockOpnames(context.Context, *ListStockOpnamesRequest) (*ListStockOpnamesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStockOpnames not implemented")
}
func (UnimplementedWarehouseServiceServer) GetStockOpname(context.Context, *GetStockOpnameRequest) (*GetStockOpnameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStockOpname not implemented")
}
func (UnimplementedWarehouseServiceServer) ListStockRequests(context.Context, *ListStockRequestsRequest) (*ListStockRequestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStockRequests not implemented")
}
func (UnimplementedWarehouseServiceServer) RequestStock(context.Context, *RequestStockRequest) (*RequestStockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestStock not implemented")
}
func (UnimplementedWarehouseServiceServer) ApproveStockRequest(context.Context, *ApproveStockRequestRequest) (*ApproveStockRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveStockRequest not implemented")
}
func (UnimplementedWarehouseServiceServer) RejectStockRequest(context.Context, *RejectStockRequestRequest) (*RejectStockRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectStockRequest not implemented")
}
func (UnimplementedWarehouseServiceServer) ShipStockRequest(context.Context, *ShipStockRequestRequest) (*ShipStockRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShipStockRequest not implemented")
}
func (UnimplementedWarehouseServiceServer) StockRequestReceived(context.Context, *StockRequestReceivedRequest) (*StockRequestReceivedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StockRequestReceived not implemented")
}
func (UnimplementedWarehouseServiceServer) mustEmbedUnimplementedWarehouseServiceServer() {}
func (UnimplementedWarehouseServiceServer) testEmbeddedByValue()                          {}

// UnsafeWarehouseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WarehouseServiceServer will
// result in compilation errors.
type UnsafeWarehouseServiceServer interface {
	mustEmbedUnimplementedWarehouseServiceServer()
}

func RegisterWarehouseServiceServer(s grpc.ServiceRegistrar, srv WarehouseServiceServer) {
	// If the following call panics, it indicates UnimplementedWarehouseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WarehouseService_ServiceDesc, srv)
}

func _WarehouseService_ListLocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).ListLocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_ListLocations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).ListLocations(ctx, req.(*ListLocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_CreateLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).CreateLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_CreateLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).CreateLocation(ctx, req.(*CreateLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_ListSuppliers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSuppliersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).ListSuppliers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_ListSuppliers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).ListSuppliers(ctx, req.(*ListSuppliersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_CreateSupplier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSupplierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).CreateSupplier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_CreateSupplier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).CreateSupplier(ctx, req.(*CreateSupplierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_CreatePurchaseOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePurchaseOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).CreatePurchaseOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_CreatePurchaseOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).CreatePurchaseOrder(ctx, req.(*CreatePurchaseOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_CreateGoodsReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGoodsReceiptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).CreateGoodsReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_CreateGoodsReceipt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).CreateGoodsReceipt(ctx, req.(*CreateGoodsReceiptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_CreateTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).CreateTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_CreateTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).CreateTransfer(ctx, req.(*CreateTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_CreateAdjustment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdjustmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).CreateAdjustment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_CreateAdjustment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).CreateAdjustment(ctx, req.(*CreateAdjustmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_CreateStockOpname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStockOpnameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).CreateStockOpname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_CreateStockOpname_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).CreateStockOpname(ctx, req.(*CreateStockOpnameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_ListStockOpnames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStockOpnamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).ListStockOpnames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_ListStockOpnames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).ListStockOpnames(ctx, req.(*ListStockOpnamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_GetStockOpname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStockOpnameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).GetStockOpname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_GetStockOpname_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).GetStockOpname(ctx, req.(*GetStockOpnameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_ListStockRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStockRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).ListStockRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_ListStockRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).ListStockRequests(ctx, req.(*ListStockRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_RequestStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).RequestStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_RequestStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).RequestStock(ctx, req.(*RequestStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_ApproveStockRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveStockRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).ApproveStockRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_ApproveStockRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).ApproveStockRequest(ctx, req.(*ApproveStockRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_RejectStockRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectStockRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).RejectStockRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_RejectStockRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).RejectStockRequest(ctx, req.(*RejectStockRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_ShipStockRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShipStockRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).ShipStockRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_ShipStockRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).ShipStockRequest(ctx, req.(*ShipStockRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WarehouseService_StockRequestReceived_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockRequestReceivedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WarehouseServiceServer).StockRequestReceived(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WarehouseService_StockRequestReceived_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WarehouseServiceServer).StockRequestReceived(ctx, req.(*StockRequestReceivedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WarehouseService_ServiceDesc is the grpc.ServiceDesc for WarehouseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WarehouseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "erposfnb.warehouse.WarehouseService",
	HandlerType: (*WarehouseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListLocations",
			Handler:    _WarehouseService_ListLocations_Handler,
		},
		{
			MethodName: "CreateLocation",
			Handler:    _WarehouseService_CreateLocation_Handler,
		},
		{
			MethodName: "ListSuppliers",
			Handler:    _WarehouseService_ListSuppliers_Handler,
		},
		{
			MethodName: "CreateSupplier",
			Handler:    _WarehouseService_CreateSupplier_Handler,
		},
		{
			MethodName: "CreatePurchaseOrder",
			Handler:    _WarehouseService_CreatePurchaseOrder_Handler,
		},
		{
			MethodName: "CreateGoodsReceipt",
			Handler:    _WarehouseService_CreateGoodsReceipt_Handler,
		},
		{
			MethodName: "CreateTransfer",
			Handler:    _WarehouseService_CreateTransfer_Handler,
		},
		{
			MethodName: "CreateAdjustment",
			Handler:    _WarehouseService_CreateAdjustment_Handler,
		},
		{
			MethodName: "CreateStockOpname",
			Handler:    _WarehouseService_CreateStockOpname_Handler,
		},
		{
			MethodName: "ListStockOpnames",
			Handler:    _WarehouseService_ListStockOpnames_Handler,
		},
		{
			MethodName: "GetStockOpname",
			Handler:    _WarehouseService_GetStockOpname_Handler,
		},
		{
			MethodName: "ListStockRequests",
			Handler:    _WarehouseService_ListStockRequests_Handler,
		},
		{
			MethodName: "RequestStock",
			Handler:    _WarehouseService_RequestStock_Handler,
		},
		{
			MethodName: "ApproveStockRequest",
			Handler:    _WarehouseService_ApproveStockRequest_Handler,
		},
		{
			MethodName: "RejectStockRequest",
			Handler:    _WarehouseService_RejectStockRequest_Handler,
		},
		{
			MethodName: "ShipStockRequest",
			Handler:    _WarehouseService_ShipStockRequest_Handler,
		},
		{
			MethodName: "StockRequestReceived",
			Handler:    _WarehouseService_StockRequestReceived_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "warehouse/warehouse.proto",
}
