// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: media/media.proto

package media

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MediaSpec points at one media location.
// scope is the root dir, one of "u", "t", or "w".
// id_ref is the owner id without dashes, id_ref_branch is empty for the user scope.
// visibility is a plain string, one of "public" or "private".
type MediaSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	IdRef         string                 `protobuf:"bytes,2,opt,name=id_ref,json=idRef,proto3" json:"id_ref,omitempty"`
	IdRefBranch   string                 `protobuf:"bytes,3,opt,name=id_ref_branch,json=idRefBranch,proto3" json:"id_ref_branch,omitempty"`
	Visibility    string                 `protobuf:"bytes,4,opt,name=visibility,proto3" json:"visibility,omitempty"`
	FileName      string                 `protobuf:"bytes,5,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaSpec) Reset() {
	*x = MediaSpec{}
	mi := &file_media_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaSpec) ProtoMessage() {}

func (x *MediaSpec) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaSpec.ProtoReflect.Descriptor instead.
func (*MediaSpec) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{0}
}

func (x *MediaSpec) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *MediaSpec) GetIdRef() string {
	if x != nil {
		return x.IdRef
	}
	return ""
}

func (x *MediaSpec) GetIdRefBranch() string {
	if x != nil {
		return x.IdRefBranch
	}
	return ""
}

func (x *MediaSpec) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *MediaSpec) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *MediaSpec) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// UploadMediaRequest writes one file and then calls the related core service
// so the metadata row lands in the owning database.
type UploadMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *MediaSpec             `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMediaRequest) Reset() {
	*x = UploadMediaRequest{}
	mi := &file_media_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMediaRequest) ProtoMessage() {}

func (x *UploadMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMediaRequest.ProtoReflect.Descriptor instead.
func (*UploadMediaRequest) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{1}
}

func (x *UploadMediaRequest) GetSpec() *MediaSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *UploadMediaRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type UploadMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Visibility    string                 `protobuf:"bytes,2,opt,name=visibility,proto3" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMediaResponse) Reset() {
	*x = UploadMediaResponse{}
	mi := &file_media_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMediaResponse) ProtoMessage() {}

func (x *UploadMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMediaResponse.ProtoReflect.Descriptor instead.
func (*UploadMediaResponse) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{2}
}

func (x *UploadMediaResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UploadMediaResponse) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

// UpdateMediaRequest replaces a file or moves it between public and private.
type UpdateMediaRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Spec               *MediaSpec             `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	PreviousPath       string                 `protobuf:"bytes,2,opt,name=previous_path,json=previousPath,proto3" json:"previous_path,omitempty"`
	PreviousVisibility string                 `protobuf:"bytes,3,opt,name=previous_visibility,json=previousVisibility,proto3" json:"previous_visibility,omitempty"`
	Content            []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateMediaRequest) Reset() {
	*x = UpdateMediaRequest{}
	mi := &file_media_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMediaRequest) ProtoMessage() {}

func (x *UpdateMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMediaRequest.ProtoReflect.Descriptor instead.
func (*UpdateMediaRequest) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMediaRequest) GetSpec() *MediaSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *UpdateMediaRequest) GetPreviousPath() string {
	if x != nil {
		return x.PreviousPath
	}
	return ""
}

func (x *UpdateMediaRequest) GetPreviousVisibility() string {
	if x != nil {
		return x.PreviousVisibility
	}
	return ""
}

func (x *UpdateMediaRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type UpdateMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Visibility    string                 `protobuf:"bytes,2,opt,name=visibility,proto3" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMediaResponse) Reset() {
	*x = UpdateMediaResponse{}
	mi := &file_media_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMediaResponse) ProtoMessage() {}

func (x *UpdateMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMediaResponse.ProtoReflect.Descriptor instead.
func (*UpdateMediaResponse) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateMediaResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UpdateMediaResponse) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

type DeleteMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Visibility    string                 `protobuf:"bytes,2,opt,name=visibility,proto3" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMediaRequest) Reset() {
	*x = DeleteMediaRequest{}
	mi := &file_media_media_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaRequest) ProtoMessage() {}

func (x *DeleteMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaRequest.ProtoReflect.Descriptor instead.
func (*DeleteMediaRequest) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteMediaRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DeleteMediaRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

type DeleteMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMediaResponse) Reset() {
	*x = DeleteMediaResponse{}
	mi := &file_media_media_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaResponse) ProtoMessage() {}

func (x *DeleteMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_media_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaResponse.ProtoReflect.Descriptor instead.
func (*DeleteMediaResponse) Descriptor() ([]byte, []int) {
	return file_media_media_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteMediaResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_media_media_proto protoreflect.FileDescriptor

const file_media_media_proto_rawDesc = "" +
	"\n" +
	"\x11media/media.proto\x12\x0eerposfnb.media\"\xbc\x01\n" +
	"\tMediaSpec\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x15\n" +
	"\x06id_ref\x18\x02 \x01(\tR\x05idRef\x12\"\n" +
	"\rid_ref_branch\x18\x03 \x01(\tR\vidRefBranch\x12\x1e\n" +
	"\n" +
	"visibility\x18\x04 \x01(\tR\n" +
	"visibility\x12\x1b\n" +
	"\tfile_name\x18\x05 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\"]\n" +
	"\x12UploadMediaRequest\x12-\n" +
	"\x04spec\x18\x01 \x01(\v2\x19.erposfnb.media.MediaSpecR\x04spec\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"I\n" +
	"\x13UploadMediaResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1e\n" +
	"\n" +
	"visibility\x18\x02 \x01(\tR\n" +
	"visibility\"\xb3\x01\n" +
	"\x12UpdateMediaRequest\x12-\n" +
	"\x04spec\x18\x01 \x01(\v2\x19.erposfnb.media.MediaSpecR\x04spec\x12#\n" +
	"\rprevious_path\x18\x02 \x01(\tR\fpreviousPath\x12/\n" +
	"\x13previous_visibility\x18\x03 \x01(\tR\x12previousVisibility\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\"I\n" +
	"\x13UpdateMediaResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1e\n" +
	"\n" +
	"visibility\x18\x02 \x01(\tR\n" +
	"visibility\"H\n" +
	"\x12DeleteMediaRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1e\n" +
	"\n" +
	"visibility\x18\x02 \x01(\tR\n" +
	"visibility\"/\n" +
	"\x13DeleteMediaResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted2\x96\x02\n" +
	"\fMediaService\x12V\n" +
	"\vUploadMedia\x12\".erposfnb.media.UploadMediaRequest\x1a#.erposfnb.media.UploadMediaResponse\x12V\n" +
	"\vUpdateMedia\x12\".erposfnb.media.UpdateMediaRequest\x1a#.erposfnb.media.UpdateMediaResponse\x12V\n" +
	"\vDeleteMedia\x12\".erposfnb.media.DeleteMediaRequest\x1a#.erposfnb.media.DeleteMediaResponseB.Z,github.com/prothegee/erposfnb-protobuf/mediab\x06proto3"

var (
	file_media_media_proto_rawDescOnce sync.Once
	file_media_media_proto_rawDescData []byte
)

func file_media_media_proto_rawDescGZIP() []byte {
	file_media_media_proto_rawDescOnce.Do(func() {
		file_media_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_media_proto_rawDesc), len(file_media_media_proto_rawDesc)))
	})
	return file_media_media_proto_rawDescData
}

var file_media_media_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_media_media_proto_goTypes = []any{
	(*MediaSpec)(nil),           // 0: erposfnb.media.MediaSpec
	(*UploadMediaRequest)(nil),  // 1: erposfnb.media.UploadMediaRequest
	(*UploadMediaResponse)(nil), // 2: erposfnb.media.UploadMediaResponse
	(*UpdateMediaRequest)(nil),  // 3: erposfnb.media.UpdateMediaRequest
	(*UpdateMediaResponse)(nil), // 4: erposfnb.media.UpdateMediaResponse
	(*DeleteMediaRequest)(nil),  // 5: erposfnb.media.DeleteMediaRequest
	(*DeleteMediaResponse)(nil), // 6: erposfnb.media.DeleteMediaResponse
}
var file_media_media_proto_depIdxs = []int32{
	0, // 0: erposfnb.media.UploadMediaRequest.spec:type_name -> erposfnb.media.MediaSpec
	0, // 1: erposfnb.media.UpdateMediaRequest.spec:type_name -> erposfnb.media.MediaSpec
	1, // 2: erposfnb.media.MediaService.UploadMedia:input_type -> erposfnb.media.UploadMediaRequest
	3, // 3: erposfnb.media.MediaService.UpdateMedia:input_type -> erposfnb.media.UpdateMediaRequest
	5, // 4: erposfnb.media.MediaService.DeleteMedia:input_type -> erposfnb.media.DeleteMediaRequest
	2, // 5: erposfnb.media.MediaService.UploadMedia:output_type -> erposfnb.media.UploadMediaResponse
	4, // 6: erposfnb.media.MediaService.UpdateMedia:output_type -> erposfnb.media.UpdateMediaResponse
	6, // 7: erposfnb.media.MediaService.DeleteMedia:output_type -> erposfnb.media.DeleteMediaResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_media_media_proto_init() }
func file_media_media_proto_init() {
	if File_media_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_media_proto_rawDesc), len(file_media_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_media_media_proto_goTypes,
		DependencyIndexes: file_media_media_proto_depIdxs,
		MessageInfos:      file_media_media_proto_msgTypes,
	}.Build()
	File_media_media_proto = out.File
	file_media_media_proto_goTypes = nil
	file_media_media_proto_depIdxs = nil
}
