// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: gateway_stream/stream.proto

package gateway_stream

import (
	common "github.com/prothegee/erposfnb-protobuf/common"
	pos "github.com/prothegee/erposfnb-protobuf/pos"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamEvent is one event pushed to the WebSocket hub and written to Kafka.
// topic is one of "orders", "kitchen", "notifications", or "stock-requests".
// payload carries the topic specific body, the typed fields below carry the
// values the stream tests assert on.
type StreamEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	OrderStatus   pos.OrderStatus        `protobuf:"varint,3,opt,name=order_status,json=orderStatus,proto3,enum=erposfnb.pos.OrderStatus" json:"order_status,omitempty"`
	PaymentStatus pos.PaymentStatus      `protobuf:"varint,4,opt,name=payment_status,json=paymentStatus,proto3,enum=erposfnb.pos.PaymentStatus" json:"payment_status,omitempty"`
	RoleAccess    common.RoleAccess      `protobuf:"varint,5,opt,name=role_access,json=roleAccess,proto3,enum=erposfnb.common.RoleAccess" json:"role_access,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEvent) Reset() {
	*x = StreamEvent{}
	mi := &file_gateway_stream_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEvent) ProtoMessage() {}

func (x *StreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_stream_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEvent.ProtoReflect.Descriptor instead.
func (*StreamEvent) Descriptor() ([]byte, []int) {
	return file_gateway_stream_stream_proto_rawDescGZIP(), []int{0}
}

func (x *StreamEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StreamEvent) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *StreamEvent) GetOrderStatus() pos.OrderStatus {
	if x != nil {
		return x.OrderStatus
	}
	return pos.OrderStatus(0)
}

func (x *StreamEvent) GetPaymentStatus() pos.PaymentStatus {
	if x != nil {
		return x.PaymentStatus
	}
	return pos.PaymentStatus(0)
}

func (x *StreamEvent) GetRoleAccess() common.RoleAccess {
	if x != nil {
		return x.RoleAccess
	}
	return common.RoleAccess(0)
}

func (x *StreamEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

// PublishRequest carries the origin service id that producer_auth tests
// against the allowed producer list.
type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginService string                 `protobuf:"bytes,1,opt,name=origin_service,json=originService,proto3" json:"origin_service,omitempty"`
	Event         *StreamEvent           `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_gateway_stream_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_stream_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_gateway_stream_stream_proto_rawDescGZIP(), []int{1}
}

func (x *PublishRequest) GetOriginService() string {
	if x != nil {
		return x.OriginService
	}
	return ""
}

func (x *PublishRequest) GetEvent() *StreamEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_gateway_stream_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_stream_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_gateway_stream_stream_proto_rawDescGZIP(), []int{2}
}

func (x *PublishResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PublishResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_gateway_stream_stream_proto protoreflect.FileDescriptor

const file_gateway_stream_stream_proto_rawDesc = "" +
	"\n" +
	"\x1bgateway_stream/stream.proto\x12\x17erposfnb.gateway_stream\x1a\x13common/common.proto\x1a\rpos/pos.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xca\x02\n" +
	"\vStreamEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12<\n" +
	"\forder_status\x18\x03 \x01(\x0e2\x19.erposfnb.pos.OrderStatusR\vorderStatus\x12B\n" +
	"\x0epayment_status\x18\x04 \x01(\x0e2\x1b.erposfnb.pos.PaymentStatusR\rpaymentStatus\x12<\n" +
	"\vrole_access\x18\x05 \x01(\x0e2\x1b.erposfnb.common.RoleAccessR\n" +
	"roleAccess\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12;\n" +
	"\voccurred_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"s\n" +
	"\x0ePublishRequest\x12%\n" +
	"\x0eorigin_service\x18\x01 \x01(\tR\roriginService\x12:\n" +
	"\x05event\x18\x02 \x01(\v2$.erposfnb.gateway_stream.StreamEventR\x05event\"H\n" +
	"\x0fPublishResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted2m\n" +
	"\rStreamService\x12\\\n" +
	"\aPublish\x12'.erposfnb.gateway_stream.PublishRequest\x1a(.erposfnb.gateway_stream.PublishResponseB7Z5github.com/prothegee/erposfnb-protobuf/gateway_streamb\x06proto3"

var (
	file_gateway_stream_stream_proto_rawDescOnce sync.Once
	file_gateway_stream_stream_proto_rawDescData []byte
)

func file_gateway_stream_stream_proto_rawDescGZIP() []byte {
	file_gateway_stream_stream_proto_rawDescOnce.Do(func() {
		file_gateway_stream_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_stream_stream_proto_rawDesc), len(file_gateway_stream_stream_proto_rawDesc)))
	})
	return file_gateway_stream_stream_proto_rawDescData
}

var file_gateway_stream_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gateway_stream_stream_proto_goTypes = []any{
	(*StreamEvent)(nil),           // 0: erposfnb.gateway_stream.StreamEvent
	(*PublishRequest)(nil),        // 1: erposfnb.gateway_stream.PublishRequest
	(*PublishResponse)(nil),       // 2: erposfnb.gateway_stream.PublishResponse
	(pos.OrderStatus)(0),          // 3: erposfnb.pos.OrderStatus
	(pos.PaymentStatus)(0),        // 4: erposfnb.pos.PaymentStatus
	(common.RoleAccess)(0),        // 5: erposfnb.common.RoleAccess
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_gateway_stream_stream_proto_depIdxs = []int32{
	3, // 0: erposfnb.gateway_stream.StreamEvent.order_status:type_name -> erposfnb.pos.OrderStatus
	4, // 1: erposfnb.gateway_stream.StreamEvent.payment_status:type_name -> erposfnb.pos.PaymentStatus
	5, // 2: erposfnb.gateway_stream.StreamEvent.role_access:type_name -> erposfnb.common.RoleAccess
	6, // 3: erposfnb.gateway_stream.StreamEvent.occurred_at:type_name -> google.protobuf.Timestamp
	0, // 4: erposfnb.gateway_stream.PublishRequest.event:type_name -> erposfnb.gateway_stream.StreamEvent
	1, // 5: erposfnb.gateway_stream.StreamService.Publish:input_type -> erposfnb.gateway_stream.PublishRequest
	2, // 6: erposfnb.gateway_stream.StreamService.Publish:output_type -> erposfnb.gateway_stream.PublishResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_gateway_stream_stream_proto_init() }
func file_gateway_stream_stream_proto_init() {
	if File_gateway_stream_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_stream_stream_proto_rawDesc), len(file_gateway_stream_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_stream_stream_proto_goTypes,
		DependencyIndexes: file_gateway_stream_stream_proto_depIdxs,
		MessageInfos:      file_gateway_stream_stream_proto_msgTypes,
	}.Build()
	File_gateway_stream_stream_proto = out.File
	file_gateway_stream_stream_proto_goTypes = nil
	file_gateway_stream_stream_proto_depIdxs = nil
}
