// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: tenant/tenant.proto

package tenant

import (
	common "github.com/prothegee/erposfnb-protobuf/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tenant is a registered business that owns one or more branches.
type Tenant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IdRef         string                 `protobuf:"bytes,2,opt,name=id_ref,json=idRef,proto3" json:"id_ref,omitempty"`
	IdOwner       string                 `protobuf:"bytes,3,opt,name=id_owner,json=idOwner,proto3" json:"id_owner,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	NameDisplay   string                 `protobuf:"bytes,5,opt,name=name_display,json=nameDisplay,proto3" json:"name_display,omitempty"`
	Banned        bool                   `protobuf:"varint,6,opt,name=banned,proto3" json:"banned,omitempty"`
	BannedReason  string                 `protobuf:"bytes,7,opt,name=banned_reason,json=bannedReason,proto3" json:"banned_reason,omitempty"`
	Registered    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=registered,proto3" json:"registered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_tenant_tenant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{0}
}

func (x *Tenant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tenant) GetIdRef() string {
	if x != nil {
		return x.IdRef
	}
	return ""
}

func (x *Tenant) GetIdOwner() string {
	if x != nil {
		return x.IdOwner
	}
	return ""
}

func (x *Tenant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tenant) GetNameDisplay() string {
	if x != nil {
		return x.NameDisplay
	}
	return ""
}

func (x *Tenant) GetBanned() bool {
	if x != nil {
		return x.Banned
	}
	return false
}

func (x *Tenant) GetBannedReason() string {
	if x != nil {
		return x.BannedReason
	}
	return ""
}

func (x *Tenant) GetRegistered() *timestamppb.Timestamp {
	if x != nil {
		return x.Registered
	}
	return nil
}

// BranchInformation is the contact and picture row of one branch.
type BranchInformation struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IdBranch          string                 `protobuf:"bytes,1,opt,name=id_branch,json=idBranch,proto3" json:"id_branch,omitempty"`
	ContactEmail      string                 `protobuf:"bytes,2,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	ContactPhone      string                 `protobuf:"bytes,3,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"`
	Latitude          float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude         float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	PreferredCurrency common.Currency        `protobuf:"varint,6,opt,name=preferred_currency,json=preferredCurrency,proto3,enum=erposfnb.common.Currency" json:"preferred_currency,omitempty"`
	PubPath           string                 `protobuf:"bytes,7,opt,name=pub_path,json=pubPath,proto3" json:"pub_path,omitempty"`
	PubPict           string                 `protobuf:"bytes,8,opt,name=pub_pict,json=pubPict,proto3" json:"pub_pict,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BranchInformation) Reset() {
	*x = BranchInformation{}
	mi := &file_tenant_tenant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BranchInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BranchInformation) ProtoMessage() {}

func (x *BranchInformation) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BranchInformation.ProtoReflect.Descriptor instead.
func (*BranchInformation) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{1}
}

func (x *BranchInformation) GetIdBranch() string {
	if x != nil {
		return x.IdBranch
	}
	return ""
}

func (x *BranchInformation) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *BranchInformation) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

func (x *BranchInformation) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *BranchInformation) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *BranchInformation) GetPreferredCurrency() common.Currency {
	if x != nil {
		return x.PreferredCurrency
	}
	return common.Currency(0)
}

func (x *BranchInformation) GetPubPath() string {
	if x != nil {
		return x.PubPath
	}
	return ""
}

func (x *BranchInformation) GetPubPict() string {
	if x != nil {
		return x.PubPict
	}
	return ""
}

// Branch is one outlet that belongs to a tenant.
type Branch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IdRef         string                 `protobuf:"bytes,2,opt,name=id_ref,json=idRef,proto3" json:"id_ref,omitempty"`
	IdTenant      string                 `protobuf:"bytes,3,opt,name=id_tenant,json=idTenant,proto3" json:"id_tenant,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	NameDisplay   string                 `protobuf:"bytes,5,opt,name=name_display,json=nameDisplay,proto3" json:"name_display,omitempty"`
	Banned        bool                   `protobuf:"varint,6,opt,name=banned,proto3" json:"banned,omitempty"`
	BannedReason  string                 `protobuf:"bytes,7,opt,name=banned_reason,json=bannedReason,proto3" json:"banned_reason,omitempty"`
	Information   *BranchInformation     `protobuf:"bytes,8,opt,name=information,proto3" json:"information,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Branch) Reset() {
	*x = Branch{}
	mi := &file_tenant_tenant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Branch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Branch) ProtoMessage() {}

func (x *Branch) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Branch.ProtoReflect.Descriptor instead.
func (*Branch) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{2}
}

func (x *Branch) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Branch) GetIdRef() string {
	if x != nil {
		return x.IdRef
	}
	return ""
}

func (x *Branch) GetIdTenant() string {
	if x != nil {
		return x.IdTenant
	}
	return ""
}

func (x *Branch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Branch) GetNameDisplay() string {
	if x != nil {
		return x.NameDisplay
	}
	return ""
}

func (x *Branch) GetBanned() bool {
	if x != nil {
		return x.Banned
	}
	return false
}

func (x *Branch) GetBannedReason() string {
	if x != nil {
		return x.BannedReason
	}
	return ""
}

func (x *Branch) GetInformation() *BranchInformation {
	if x != nil {
		return x.Information
	}
	return nil
}

// Member is one account that holds a role in a tenant branch.
type Member struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IdTenant       string                 `protobuf:"bytes,2,opt,name=id_tenant,json=idTenant,proto3" json:"id_tenant,omitempty"`
	IdTenantBranch string                 `protobuf:"bytes,3,opt,name=id_tenant_branch,json=idTenantBranch,proto3" json:"id_tenant_branch,omitempty"`
	IdAccountUser  string                 `protobuf:"bytes,4,opt,name=id_account_user,json=idAccountUser,proto3" json:"id_account_user,omitempty"`
	Access         common.RoleAccess      `protobuf:"varint,5,opt,name=access,proto3,enum=erposfnb.common.RoleAccess" json:"access,omitempty"`
	AddedAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_tenant_tenant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{3}
}

func (x *Member) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Member) GetIdTenant() string {
	if x != nil {
		return x.IdTenant
	}
	return ""
}

func (x *Member) GetIdTenantBranch() string {
	if x != nil {
		return x.IdTenantBranch
	}
	return ""
}

func (x *Member) GetIdAccountUser() string {
	if x != nil {
		return x.IdAccountUser
	}
	return ""
}

func (x *Member) GetAccess() common.RoleAccess {
	if x != nil {
		return x.Access
	}
	return common.RoleAccess(0)
}

func (x *Member) GetAddedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AddedAt
	}
	return nil
}

type CreateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdOwner       string                 `protobuf:"bytes,1,opt,name=id_owner,json=idOwner,proto3" json:"id_owner,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NameDisplay   string                 `protobuf:"bytes,3,opt,name=name_display,json=nameDisplay,proto3" json:"name_display,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantRequest) Reset() {
	*x = CreateTenantRequest{}
	mi := &file_tenant_tenant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantRequest) ProtoMessage() {}

func (x *CreateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantRequest.ProtoReflect.Descriptor instead.
func (*CreateTenantRequest) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTenantRequest) GetIdOwner() string {
	if x != nil {
		return x.IdOwner
	}
	return ""
}

func (x *CreateTenantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTenantRequest) GetNameDisplay() string {
	if x != nil {
		return x.NameDisplay
	}
	return ""
}

type CreateTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *Tenant                `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantResponse) Reset() {
	*x = CreateTenantResponse{}
	mi := &file_tenant_tenant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantResponse) ProtoMessage() {}

func (x *CreateTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantResponse.ProtoReflect.Descriptor instead.
func (*CreateTenantResponse) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTenantResponse) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

type ListTenantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdOwner       string                 `protobuf:"bytes,1,opt,name=id_owner,json=idOwner,proto3" json:"id_owner,omitempty"`
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsRequest) Reset() {
	*x = ListTenantsRequest{}
	mi := &file_tenant_tenant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsRequest) ProtoMessage() {}

func (x *ListTenantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsRequest.ProtoReflect.Descriptor instead.
func (*ListTenantsRequest) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{6}
}

func (x *ListTenantsRequest) GetIdOwner() string {
	if x != nil {
		return x.IdOwner
	}
	return ""
}

func (x *ListTenantsRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTenantsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListTenantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenants       []*Tenant              `protobuf:"bytes,1,rep,name=tenants,proto3" json:"tenants,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsResponse) Reset() {
	*x = ListTenantsResponse{}
	mi := &file_tenant_tenant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsResponse) ProtoMessage() {}

func (x *ListTenantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsResponse.ProtoReflect.Descriptor instead.
func (*ListTenantsResponse) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{7}
}

func (x *ListTenantsResponse) GetTenants() []*Tenant {
	if x != nil {
		return x.Tenants
	}
	return nil
}

func (x *ListTenantsResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantRequest) Reset() {
	*x = GetTenantRequest{}
	mi := &file_tenant_tenant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantRequest) ProtoMessage() {}

func (x *GetTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantRequest.ProtoReflect.Descriptor instead.
func (*GetTenantRequest) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{8}
}

func (x *GetTenantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *Tenant                `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantResponse) Reset() {
	*x = GetTenantResponse{}
	mi := &file_tenant_tenant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantResponse) ProtoMessage() {}

func (x *GetTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantResponse.ProtoReflect.Descriptor instead.
func (*GetTenantResponse) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{9}
}

func (x *GetTenantResponse) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

type UpdateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NameDisplay   string                 `protobuf:"bytes,2,opt,name=name_display,json=nameDisplay,proto3" json:"name_display,omitempty"`
	Banned        bool                   `protobuf:"varint,3,opt,name=banned,proto3" json:"banned,omitempty"`
	BannedReason  string                 `protobuf:"bytes,4,opt,name=banned_reason,json=bannedReason,proto3" json:"banned_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTenantRequest) Reset() {
	*x = UpdateTenantRequest{}
	mi := &file_tenant_tenant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantRequest) ProtoMessage() {}

func (x *UpdateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantRequest.ProtoReflect.Descriptor instead.
func (*UpdateTenantRequest) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateTenantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTenantRequest) GetNameDisplay() string {
	if x != nil {
		return x.NameDisplay
	}
	return ""
}

func (x *UpdateTenantRequest) GetBanned() bool {
	if x != nil {
		return x.Banned
	}
	return false
}

func (x *UpdateTenantRequest) GetBannedReason() string {
	if x != nil {
		return x.BannedReason
	}
	return ""
}

type UpdateTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *Tenant                `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTenantResponse) Reset() {
	*x = UpdateTenantResponse{}
	mi := &file_tenant_tenant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantResponse) ProtoMessage() {}

func (x *UpdateTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantResponse.ProtoReflect.Descriptor instead.
func (*UpdateTenantResponse) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateTenantResponse) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

type CreateBranchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdTenant      string                 `protobuf:"bytes,1,opt,name=id_tenant,json=idTenant,proto3" json:"id_tenant,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NameDisplay   string                 `protobuf:"bytes,3,opt,name=name_display,json=nameDisplay,proto3" json:"name_display,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBranchRequest) Reset() {
	*x = CreateBranchRequest{}
	mi := &file_tenant_tenant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBranchRequest) ProtoMessage() {}

func (x *CreateBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBranchRequest.ProtoReflect.Descriptor instead.
func (*CreateBranchRequest) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{12}
}

func (x *CreateBranchRequest) GetIdTenant() string {
	if x != nil {
		return x.IdTenant
	}
	return ""
}

func (x *CreateBranchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBranchRequest) GetNameDisplay() string {
	if x != nil {
		return x.NameDisplay
	}
	return ""
}

type CreateBranchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branch        *Branch                `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBranchResponse) Reset() {
	*x = CreateBranchResponse{}
	mi := &file_tenant_tenant_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBranchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBranchResponse) ProtoMessage() {}

func (x *CreateBranchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBranchResponse.ProtoReflect.Descriptor instead.
func (*CreateBranchResponse) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{13}
}

func (x *CreateBranchResponse) GetBranch() *Branch {
	if x != nil {
		return x.Branch
	}
	return nil
}

type ListBranchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdTenant      string                 `protobuf:"bytes,1,opt,name=id_tenant,json=idTenant,proto3" json:"id_tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBranchesRequest) Reset() {
	*x = ListBranchesRequest{}
	mi := &file_tenant_tenant_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBranchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBranchesRequest) ProtoMessage() {}

func (x *ListBranchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBranchesRequest.ProtoReflect.Descriptor instead.
func (*ListBranchesRequest) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{14}
}

func (x *ListBranchesRequest) GetIdTenant() string {
	if x != nil {
		return x.IdTenant
	}
	return ""
}

type ListBranchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branches      []*Branch              `protobuf:"bytes,1,rep,name=branches,proto3" json:"branches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBranchesResponse) Reset() {
	*x = ListBranchesResponse{}
	mi := &file_tenant_tenant_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBranchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBranchesResponse) ProtoMessage() {}

func (x *ListBranchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBranchesResponse.ProtoReflect.Descriptor instead.
func (*ListBranchesResponse) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{15}
}

func (x *ListBranchesResponse) GetBranches() []*Branch {
	if x != nil {
		return x.Branches
	}
	return nil
}

type GetBranchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBranchRequest) Reset() {
	*x = GetBranchRequest{}
	mi := &file_tenant_tenant_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBranchRequest) ProtoMessage() {}

func (x *GetBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBranchRequest.ProtoReflect.Descriptor instead.
func (*GetBranchRequest) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{16}
}

func (x *GetBranchRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetBranchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branch        *Branch                `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBranchResponse) Reset() {
	*x = GetBranchResponse{}
	mi := &file_tenant_tenant_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBranchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBranchResponse) ProtoMessage() {}

func (x *GetBranchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBranchResponse.ProtoReflect.Descriptor instead.
func (*GetBranchResponse) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{17}
}

func (x *GetBranchResponse) GetBranch() *Branch {
	if x != nil {
		return x.Branch
	}
	return nil
}

type UpdateBranchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NameDisplay   string                 `protobuf:"bytes,2,opt,name=name_display,json=nameDisplay,proto3" json:"name_display,omitempty"`
	Banned        bool                   `protobuf:"varint,3,opt,name=banned,proto3" json:"banned,omitempty"`
	BannedReason  string                 `protobuf:"bytes,4,opt,name=banned_reason,json=bannedReason,proto3" json:"banned_reason,omitempty"`
	Information   *BranchInformation     `protobuf:"bytes,5,opt,name=information,proto3" json:"information,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBranchRequest) Reset() {
	*x = UpdateBranchRequest{}
	mi := &file_tenant_tenant_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBranchRequest) ProtoMessage() {}

func (x *UpdateBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBranchRequest.ProtoReflect.Descriptor instead.
func (*UpdateBranchRequest) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateBranchRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBranchRequest) GetNameDisplay() string {
	if x != nil {
		return x.NameDisplay
	}
	return ""
}

func (x *UpdateBranchRequest) GetBanned() bool {
	if x != nil {
		return x.Banned
	}
	return false
}

func (x *UpdateBranchRequest) GetBannedReason() string {
	if x != nil {
		return x.BannedReason
	}
	return ""
}

func (x *UpdateBranchRequest) GetInformation() *BranchInformation {
	if x != nil {
		return x.Information
	}
	return nil
}

type UpdateBranchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branch        *Branch                `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBranchResponse) Reset() {
	*x = UpdateBranchResponse{}
	mi := &file_tenant_tenant_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBranchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBranchResponse) ProtoMessage() {}

func (x *UpdateBranchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBranchResponse.ProtoReflect.Descriptor instead.
func (*UpdateBranchResponse) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateBranchResponse) GetBranch() *Branch {
	if x != nil {
		return x.Branch
	}
	return nil
}

type ListMembersRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdTenantBranch string                 `protobuf:"bytes,1,opt,name=id_tenant_branch,json=idTenantBranch,proto3" json:"id_tenant_branch,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_tenant_tenant_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{20}
}

func (x *ListMembersRequest) GetIdTenantBranch() string {
	if x != nil {
		return x.IdTenantBranch
	}
	return ""
}

type ListMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*Member              `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_tenant_tenant_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{21}
}

func (x *ListMembersResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

// ListMembersByIdAccountRequest asks for every branch membership of one account.
// Account calls it at sign in and at refresh to fill the tenant_id, branch_id,
// and role_access claims of the access token.
type ListMembersByIdAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdAccountUser string                 `protobuf:"bytes,1,opt,name=id_account_user,json=idAccountUser,proto3" json:"id_account_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersByIdAccountRequest) Reset() {
	*x = ListMembersByIdAccountRequest{}
	mi := &file_tenant_tenant_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersByIdAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersByIdAccountRequest) ProtoMessage() {}

func (x *ListMembersByIdAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersByIdAccountRequest.ProtoReflect.Descriptor instead.
func (*ListMembersByIdAccountRequest) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{22}
}

func (x *ListMembersByIdAccountRequest) GetIdAccountUser() string {
	if x != nil {
		return x.IdAccountUser
	}
	return ""
}

type ListMembersByIdAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*Member              `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersByIdAccountResponse) Reset() {
	*x = ListMembersByIdAccountResponse{}
	mi := &file_tenant_tenant_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersByIdAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersByIdAccountResponse) ProtoMessage() {}

func (x *ListMembersByIdAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersByIdAccountResponse.ProtoReflect.Descriptor instead.
func (*ListMembersByIdAccountResponse) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{23}
}

func (x *ListMembersByIdAccountResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

type AddMemberRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdTenant       string                 `protobuf:"bytes,1,opt,name=id_tenant,json=idTenant,proto3" json:"id_tenant,omitempty"`
	IdTenantBranch string                 `protobuf:"bytes,2,opt,name=id_tenant_branch,json=idTenantBranch,proto3" json:"id_tenant_branch,omitempty"`
	IdAccountUser  string                 `protobuf:"bytes,3,opt,name=id_account_user,json=idAccountUser,proto3" json:"id_account_user,omitempty"`
	Access         common.RoleAccess      `protobuf:"varint,4,opt,name=access,proto3,enum=erposfnb.common.RoleAccess" json:"access,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddMemberRequest) Reset() {
	*x = AddMemberRequest{}
	mi := &file_tenant_tenant_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberRequest) ProtoMessage() {}

func (x *AddMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberRequest.ProtoReflect.Descriptor instead.
func (*AddMemberRequest) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{24}
}

func (x *AddMemberRequest) GetIdTenant() string {
	if x != nil {
		return x.IdTenant
	}
	return ""
}

func (x *AddMemberRequest) GetIdTenantBranch() string {
	if x != nil {
		return x.IdTenantBranch
	}
	return ""
}

func (x *AddMemberRequest) GetIdAccountUser() string {
	if x != nil {
		return x.IdAccountUser
	}
	return ""
}

func (x *AddMemberRequest) GetAccess() common.RoleAccess {
	if x != nil {
		return x.Access
	}
	return common.RoleAccess(0)
}

type AddMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *Member                `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberResponse) Reset() {
	*x = AddMemberResponse{}
	mi := &file_tenant_tenant_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberResponse) ProtoMessage() {}

func (x *AddMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberResponse.ProtoReflect.Descriptor instead.
func (*AddMemberResponse) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{25}
}

func (x *AddMemberResponse) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

type UpdateMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Access        common.RoleAccess      `protobuf:"varint,2,opt,name=access,proto3,enum=erposfnb.common.RoleAccess" json:"access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemberRequest) Reset() {
	*x = UpdateMemberRequest{}
	mi := &file_tenant_tenant_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberRequest) ProtoMessage() {}

func (x *UpdateMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberRequest.ProtoReflect.Descriptor instead.
func (*UpdateMemberRequest) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateMemberRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMemberRequest) GetAccess() common.RoleAccess {
	if x != nil {
		return x.Access
	}
	return common.RoleAccess(0)
}

type UpdateMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *Member                `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemberResponse) Reset() {
	*x = UpdateMemberResponse{}
	mi := &file_tenant_tenant_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberResponse) ProtoMessage() {}

func (x *UpdateMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberResponse.ProtoReflect.Descriptor instead.
func (*UpdateMemberResponse) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateMemberResponse) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

type RemoveMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	mi := &file_tenant_tenant_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{28}
}

func (x *RemoveMemberRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removed       bool                   `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberResponse) Reset() {
	*x = RemoveMemberResponse{}
	mi := &file_tenant_tenant_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberResponse) ProtoMessage() {}

func (x *RemoveMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveMemberResponse) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{29}
}

func (x *RemoveMemberResponse) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

type SummarizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdTenant      string                 `protobuf:"bytes,1,opt,name=id_tenant,json=idTenant,proto3" json:"id_tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeRequest) Reset() {
	*x = SummarizeRequest{}
	mi := &file_tenant_tenant_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeRequest) ProtoMessage() {}

func (x *SummarizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeRequest.ProtoReflect.Descriptor instead.
func (*SummarizeRequest) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{30}
}

func (x *SummarizeRequest) GetIdTenant() string {
	if x != nil {
		return x.IdTenant
	}
	return ""
}

type SummarizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeResponse) Reset() {
	*x = SummarizeResponse{}
	mi := &file_tenant_tenant_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeResponse) ProtoMessage() {}

func (x *SummarizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeResponse.ProtoReflect.Descriptor instead.
func (*SummarizeResponse) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{31}
}

func (x *SummarizeResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

// CheckBannedRequest carries the tenant id that account tests at sign in and refresh.
type CheckBannedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdTenant      string                 `protobuf:"bytes,1,opt,name=id_tenant,json=idTenant,proto3" json:"id_tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckBannedRequest) Reset() {
	*x = CheckBannedRequest{}
	mi := &file_tenant_tenant_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBannedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBannedRequest) ProtoMessage() {}

func (x *CheckBannedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBannedRequest.ProtoReflect.Descriptor instead.
func (*CheckBannedRequest) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{32}
}

func (x *CheckBannedRequest) GetIdTenant() string {
	if x != nil {
		return x.IdTenant
	}
	return ""
}

type CheckBannedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Banned        bool                   `protobuf:"varint,1,opt,name=banned,proto3" json:"banned,omitempty"`
	BannedReason  string                 `protobuf:"bytes,2,opt,name=banned_reason,json=bannedReason,proto3" json:"banned_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckBannedResponse) Reset() {
	*x = CheckBannedResponse{}
	mi := &file_tenant_tenant_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBannedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBannedResponse) ProtoMessage() {}

func (x *CheckBannedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_tenant_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBannedResponse.ProtoReflect.Descriptor instead.
func (*CheckBannedResponse) Descriptor() ([]byte, []int) {
	return file_tenant_tenant_proto_rawDescGZIP(), []int{33}
}

func (x *CheckBannedResponse) GetBanned() bool {
	if x != nil {
		return x.Banned
	}
	return false
}

func (x *CheckBannedResponse) GetBannedReason() string {
	if x != nil {
		return x.BannedReason
	}
	return ""
}

var File_tenant_tenant_proto protoreflect.FileDescriptor

const file_tenant_tenant_proto_rawDesc = "" +
	"\n" +
	"\x13tenant/tenant.proto\x12\x0ferposfnb.tenant\x1a\x13common/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfa\x01\n" +
	"\x06Tenant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06id_ref\x18\x02 \x01(\tR\x05idRef\x12\x19\n" +
	"\bid_owner\x18\x03 \x01(\tR\aidOwner\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12!\n" +
	"\fname_display\x18\x05 \x01(\tR\vnameDisplay\x12\x16\n" +
	"\x06banned\x18\x06 \x01(\bR\x06banned\x12#\n" +
	"\rbanned_reason\x18\a \x01(\tR\fbannedReason\x12:\n" +
	"\n" +
	"registered\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"registered\"\xb4\x02\n" +
	"\x11BranchInformation\x12\x1b\n" +
	"\tid_branch\x18\x01 \x01(\tR\bidBranch\x12#\n" +
	"\rcontact_email\x18\x02 \x01(\tR\fcontactEmail\x12#\n" +
	"\rcontact_phone\x18\x03 \x01(\tR\fcontactPhone\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\x12H\n" +
	"\x12preferred_currency\x18\x06 \x01(\x0e2\x19.erposfnb.common.CurrencyR\x11preferredCurrency\x12\x19\n" +
	"\bpub_path\x18\a \x01(\tR\apubPath\x12\x19\n" +
	"\bpub_pict\x18\b \x01(\tR\apubPict\"\x86\x02\n" +
	"\x06Branch\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06id_ref\x18\x02 \x01(\tR\x05idRef\x12\x1b\n" +
	"\tid_tenant\x18\x03 \x01(\tR\bidTenant\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12!\n" +
	"\fname_display\x18\x05 \x01(\tR\vnameDisplay\x12\x16\n" +
	"\x06banned\x18\x06 \x01(\bR\x06banned\x12#\n" +
	"\rbanned_reason\x18\a \x01(\tR\fbannedReason\x12D\n" +
	"\vinformation\x18\b \x01(\v2\".erposfnb.tenant.BranchInformationR\vinformation\"\xf3\x01\n" +
	"\x06Member\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tid_tenant\x18\x02 \x01(\tR\bidTenant\x12(\n" +
	"\x10id_tenant_branch\x18\x03 \x01(\tR\x0eidTenantBranch\x12&\n" +
	"\x0fid_account_user\x18\x04 \x01(\tR\ridAccountUser\x123\n" +
	"\x06access\x18\x05 \x01(\x0e2\x1b.erposfnb.common.RoleAccessR\x06access\x125\n" +
	"\badded_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aaddedAt\"g\n" +
	"\x13CreateTenantRequest\x12\x19\n" +
	"\bid_owner\x18\x01 \x01(\tR\aidOwner\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fname_display\x18\x03 \x01(\tR\vnameDisplay\"G\n" +
	"\x14CreateTenantResponse\x12/\n" +
	"\x06tenant\x18\x01 \x01(\v2\x17.erposfnb.tenant.TenantR\x06tenant\"`\n" +
	"\x12ListTenantsRequest\x12\x19\n" +
	"\bid_owner\x18\x01 \x01(\tR\aidOwner\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\"^\n" +
	"\x13ListTenantsResponse\x121\n" +
	"\atenants\x18\x01 \x03(\v2\x17.erposfnb.tenant.TenantR\atenants\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\"\"\n" +
	"\x10GetTenantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x11GetTenantResponse\x12/\n" +
	"\x06tenant\x18\x01 \x01(\v2\x17.erposfnb.tenant.TenantR\x06tenant\"\x85\x01\n" +
	"\x13UpdateTenantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fname_display\x18\x02 \x01(\tR\vnameDisplay\x12\x16\n" +
	"\x06banned\x18\x03 \x01(\bR\x06banned\x12#\n" +
	"\rbanned_reason\x18\x04 \x01(\tR\fbannedReason\"G\n" +
	"\x14UpdateTenantResponse\x12/\n" +
	"\x06tenant\x18\x01 \x01(\v2\x17.erposfnb.tenant.TenantR\x06tenant\"i\n" +
	"\x13CreateBranchRequest\x12\x1b\n" +
	"\tid_tenant\x18\x01 \x01(\tR\bidTenant\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fname_display\x18\x03 \x01(\tR\vnameDisplay\"G\n" +
	"\x14CreateBranchResponse\x12/\n" +
	"\x06branch\x18\x01 \x01(\v2\x17.erposfnb.tenant.BranchR\x06branch\"2\n" +
	"\x13ListBranchesRequest\x12\x1b\n" +
	"\tid_tenant\x18\x01 \x01(\tR\bidTenant\"K\n" +
	"\x14ListBranchesResponse\x123\n" +
	"\bbranches\x18\x01 \x03(\v2\x17.erposfnb.tenant.BranchR\bbranches\"\"\n" +
	"\x10GetBranchRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x11GetBranchResponse\x12/\n" +
	"\x06branch\x18\x01 \x01(\v2\x17.erposfnb.tenant.BranchR\x06branch\"\xcb\x01\n" +
	"\x13UpdateBranchRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fname_display\x18\x02 \x01(\tR\vnameDisplay\x12\x16\n" +
	"\x06banned\x18\x03 \x01(\bR\x06banned\x12#\n" +
	"\rbanned_reason\x18\x04 \x01(\tR\fbannedReason\x12D\n" +
	"\vinformation\x18\x05 \x01(\v2\".erposfnb.tenant.BranchInformationR\vinformation\"G\n" +
	"\x14UpdateBranchResponse\x12/\n" +
	"\x06branch\x18\x01 \x01(\v2\x17.erposfnb.tenant.BranchR\x06branch\">\n" +
	"\x12ListMembersRequest\x12(\n" +
	"\x10id_tenant_branch\x18\x01 \x01(\tR\x0eidTenantBranch\"H\n" +
	"\x13ListMembersResponse\x121\n" +
	"\amembers\x18\x01 \x03(\v2\x17.erposfnb.tenant.MemberR\amembers\"G\n" +
	"\x1dListMembersByIdAccountRequest\x12&\n" +
	"\x0fid_account_user\x18\x01 \x01(\tR\ridAccountUser\"S\n" +
	"\x1eListMembersByIdAccountResponse\x121\n" +
	"\amembers\x18\x01 \x03(\v2\x17.erposfnb.tenant.MemberR\amembers\"\xb6\x01\n" +
	"\x10AddMemberRequest\x12\x1b\n" +
	"\tid_tenant\x18\x01 \x01(\tR\bidTenant\x12(\n" +
	"\x10id_tenant_branch\x18\x02 \x01(\tR\x0eidTenantBranch\x12&\n" +
	"\x0fid_account_user\x18\x03 \x01(\tR\ridAccountUser\x123\n" +
	"\x06access\x18\x04 \x01(\x0e2\x1b.erposfnb.common.RoleAccessR\x06access\"D\n" +
	"\x11AddMemberResponse\x12/\n" +
	"\x06member\x18\x01 \x01(\v2\x17.erposfnb.tenant.MemberR\x06member\"Z\n" +
	"\x13UpdateMemberRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x123\n" +
	"\x06access\x18\x02 \x01(\x0e2\x1b.erposfnb.common.RoleAccessR\x06access\"G\n" +
	"\x14UpdateMemberResponse\x12/\n" +
	"\x06member\x18\x01 \x01(\v2\x17.erposfnb.tenant.MemberR\x06member\"%\n" +
	"\x13RemoveMemberRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x14RemoveMemberResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\bR\aremoved\"/\n" +
	"\x10SummarizeRequest\x12\x1b\n" +
	"\tid_tenant\x18\x01 \x01(\tR\bidTenant\"-\n" +
	"\x11SummarizeResponse\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\"1\n" +
	"\x12CheckBannedRequest\x12\x1b\n" +
	"\tid_tenant\x18\x01 \x01(\tR\bidTenant\"R\n" +
	"\x13CheckBannedResponse\x12\x16\n" +
	"\x06banned\x18\x01 \x01(\bR\x06banned\x12#\n" +
	"\rbanned_reason\x18\x02 \x01(\tR\fbannedReason2\xf3\n" +
	"\n" +
	"\rTenantService\x12[\n" +
	"\fCreateTenant\x12$.erposfnb.tenant.CreateTenantRequest\x1a%.erposfnb.tenant.CreateTenantResponse\x12X\n" +
	"\vListTenants\x12#.erposfnb.tenant.ListTenantsRequest\x1a$.erposfnb.tenant.ListTenantsResponse\x12R\n" +
	"\tGetTenant\x12!.erposfnb.tenant.GetTenantRequest\x1a\".erposfnb.tenant.GetTenantResponse\x12[\n" +
	"\fUpdateTenant\x12$.erposfnb.tenant.UpdateTenantRequest\x1a%.erposfnb.tenant.UpdateTenantResponse\x12[\n" +
	"\fCreateBranch\x12$.erposfnb.tenant.CreateBranchRequest\x1a%.erposfnb.tenant.CreateBranchResponse\x12[\n" +
	"\fListBranches\x12$.erposfnb.tenant.ListBranchesRequest\x1a%.erposfnb.tenant.ListBranchesResponse\x12R\n" +
	"\tGetBranch\x12!.erposfnb.tenant.GetBranchRequest\x1a\".erposfnb.tenant.GetBranchResponse\x12[\n" +
	"\fUpdateBranch\x12$.erposfnb.tenant.UpdateBranchRequest\x1a%.erposfnb.tenant.UpdateBranchResponse\x12X\n" +
	"\vListMembers\x12#.erposfnb.tenant.ListMembersRequest\x1a$.erposfnb.tenant.ListMembersResponse\x12y\n" +
	"\x16ListMembersByIdAccount\x12..erposfnb.tenant.ListMembersByIdAccountRequest\x1a/.erposfnb.tenant.ListMembersByIdAccountResponse\x12R\n" +
	"\tAddMember\x12!.erposfnb.tenant.AddMemberRequest\x1a\".erposfnb.tenant.AddMemberResponse\x12[\n" +
	"\fUpdateMember\x12$.erposfnb.tenant.UpdateMemberRequest\x1a%.erposfnb.tenant.UpdateMemberResponse\x12[\n" +
	"\fRemoveMember\x12$.erposfnb.tenant.RemoveMemberRequest\x1a%.erposfnb.tenant.RemoveMemberResponse\x12R\n" +
	"\tSummarize\x12!.erposfnb.tenant.SummarizeRequest\x1a\".erposfnb.tenant.SummarizeResponse\x12X\n" +
	"\vCheckBanned\x12#.erposfnb.tenant.CheckBannedRequest\x1a$.erposfnb.tenant.CheckBannedResponseB/Z-github.com/prothegee/erposfnb-protobuf/tenantb\x06proto3"

var (
	file_tenant_tenant_proto_rawDescOnce sync.Once
	file_tenant_tenant_proto_rawDescData []byte
)

func file_tenant_tenant_proto_rawDescGZIP() []byte {
	file_tenant_tenant_proto_rawDescOnce.Do(func() {
		file_tenant_tenant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tenant_tenant_proto_rawDesc), len(file_tenant_tenant_proto_rawDesc)))
	})
	return file_tenant_tenant_proto_rawDescData
}

var file_tenant_tenant_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_tenant_tenant_proto_goTypes = []any{
	(*Tenant)(nil),                         // 0: erposfnb.tenant.Tenant
	(*BranchInformation)(nil),              // 1: erposfnb.tenant.BranchInformation
	(*Branch)(nil),                         // 2: erposfnb.tenant.Branch
	(*Member)(nil),                         // 3: erposfnb.tenant.Member
	(*CreateTenantRequest)(nil),            // 4: erposfnb.tenant.CreateTenantRequest
	(*CreateTenantResponse)(nil),           // 5: erposfnb.tenant.CreateTenantResponse
	(*ListTenantsRequest)(nil),             // 6: erposfnb.tenant.ListTenantsRequest
	(*ListTenantsResponse)(nil),            // 7: erposfnb.tenant.ListTenantsResponse
	(*GetTenantRequest)(nil),               // 8: erposfnb.tenant.GetTenantRequest
	(*GetTenantResponse)(nil),              // 9: erposfnb.tenant.GetTenantResponse
	(*UpdateTenantRequest)(nil),            // 10: erposfnb.tenant.UpdateTenantRequest
	(*UpdateTenantResponse)(nil),           // 11: erposfnb.tenant.UpdateTenantResponse
	(*CreateBranchRequest)(nil),            // 12: erposfnb.tenant.CreateBranchRequest
	(*CreateBranchResponse)(nil),           // 13: erposfnb.tenant.CreateBranchResponse
	(*ListBranchesRequest)(nil),            // 14: erposfnb.tenant.ListBranchesRequest
	(*ListBranchesResponse)(nil),           // 15: erposfnb.tenant.ListBranchesResponse
	(*GetBranchRequest)(nil),               // 16: erposfnb.tenant.GetBranchRequest
	(*GetBranchResponse)(nil),              // 17: erposfnb.tenant.GetBranchResponse
	(*UpdateBranchRequest)(nil),            // 18: erposfnb.tenant.UpdateBranchRequest
	(*UpdateBranchResponse)(nil),           // 19: erposfnb.tenant.UpdateBranchResponse
	(*ListMembersRequest)(nil),             // 20: erposfnb.tenant.ListMembersRequest
	(*ListMembersResponse)(nil),            // 21: erposfnb.tenant.ListMembersResponse
	(*ListMembersByIdAccountRequest)(nil),  // 22: erposfnb.tenant.ListMembersByIdAccountRequest
	(*ListMembersByIdAccountResponse)(nil), // 23: erposfnb.tenant.ListMembersByIdAccountResponse
	(*AddMemberRequest)(nil),               // 24: erposfnb.tenant.AddMemberRequest
	(*AddMemberResponse)(nil),              // 25: erposfnb.tenant.AddMemberResponse
	(*UpdateMemberRequest)(nil),            // 26: erposfnb.tenant.UpdateMemberRequest
	(*UpdateMemberResponse)(nil),           // 27: erposfnb.tenant.UpdateMemberResponse
	(*RemoveMemberRequest)(nil),            // 28: erposfnb.tenant.RemoveMemberRequest
	(*RemoveMemberResponse)(nil),           // 29: erposfnb.tenant.RemoveMemberResponse
	(*SummarizeRequest)(nil),               // 30: erposfnb.tenant.SummarizeRequest
	(*SummarizeResponse)(nil),              // 31: erposfnb.tenant.SummarizeResponse
	(*CheckBannedRequest)(nil),             // 32: erposfnb.tenant.CheckBannedRequest
	(*CheckBannedResponse)(nil),            // 33: erposfnb.tenant.CheckBannedResponse
	(*timestamppb.Timestamp)(nil),          // 34: google.protobuf.Timestamp
	(common.Currency)(0),                   // 35: erposfnb.common.Currency
	(common.RoleAccess)(0),                 // 36: erposfnb.common.RoleAccess
}
var file_tenant_tenant_proto_depIdxs = []int32{
	34, // 0: erposfnb.tenant.Tenant.registered:type_name -> google.protobuf.Timestamp
	35, // 1: erposfnb.tenant.BranchInformation.preferred_currency:type_name -> erposfnb.common.Currency
	1,  // 2: erposfnb.tenant.Branch.information:type_name -> erposfnb.tenant.BranchInformation
	36, // 3: erposfnb.tenant.Member.access:type_name -> erposfnb.common.RoleAccess
	34, // 4: erposfnb.tenant.Member.added_at:type_name -> google.protobuf.Timestamp
	0,  // 5: erposfnb.tenant.CreateTenantResponse.tenant:type_name -> erposfnb.tenant.Tenant
	0,  // 6: erposfnb.tenant.ListTenantsResponse.tenants:type_name -> erposfnb.tenant.Tenant
	0,  // 7: erposfnb.tenant.GetTenantResponse.tenant:type_name -> erposfnb.tenant.Tenant
	0,  // 8: erposfnb.tenant.UpdateTenantResponse.tenant:type_name -> erposfnb.tenant.Tenant
	2,  // 9: erposfnb.tenant.CreateBranchResponse.branch:type_name -> erposfnb.tenant.Branch
	2,  // 10: erposfnb.tenant.ListBranchesResponse.branches:type_name -> erposfnb.tenant.Branch
	2,  // 11: erposfnb.tenant.GetBranchResponse.branch:type_name -> erposfnb.tenant.Branch
	1,  // 12: erposfnb.tenant.UpdateBranchRequest.information:type_name -> erposfnb.tenant.BranchInformation
	2,  // 13: erposfnb.tenant.UpdateBranchResponse.branch:type_name -> erposfnb.tenant.Branch
	3,  // 14: erposfnb.tenant.ListMembersResponse.members:type_name -> erposfnb.tenant.Member
	3,  // 15: erposfnb.tenant.ListMembersByIdAccountResponse.members:type_name -> erposfnb.tenant.Member
	36, // 16: erposfnb.tenant.AddMemberRequest.access:type_name -> erposfnb.common.RoleAccess
	3,  // 17: erposfnb.tenant.AddMemberResponse.member:type_name -> erposfnb.tenant.Member
	36, // 18: erposfnb.tenant.UpdateMemberRequest.access:type_name -> erposfnb.common.RoleAccess
	3,  // 19: erposfnb.tenant.UpdateMemberResponse.member:type_name -> erposfnb.tenant.Member
	4,  // 20: erposfnb.tenant.TenantService.CreateTenant:input_type -> erposfnb.tenant.CreateTenantRequest
	6,  // 21: erposfnb.tenant.TenantService.ListTenants:input_type -> erposfnb.tenant.ListTenantsRequest
	8,  // 22: erposfnb.tenant.TenantService.GetTenant:input_type -> erposfnb.tenant.GetTenantRequest
	10, // 23: erposfnb.tenant.TenantService.UpdateTenant:input_type -> erposfnb.tenant.UpdateTenantRequest
	12, // 24: erposfnb.tenant.TenantService.CreateBranch:input_type -> erposfnb.tenant.CreateBranchRequest
	14, // 25: erposfnb.tenant.TenantService.ListBranches:input_type -> erposfnb.tenant.ListBranchesRequest
	16, // 26: erposfnb.tenant.TenantService.GetBranch:input_type -> erposfnb.tenant.GetBranchRequest
	18, // 27: erposfnb.tenant.TenantService.UpdateBranch:input_type -> erposfnb.tenant.UpdateBranchRequest
	20, // 28: erposfnb.tenant.TenantService.ListMembers:input_type -> erposfnb.tenant.ListMembersRequest
	22, // 29: erposfnb.tenant.TenantService.ListMembersByIdAccount:input_type -> erposfnb.tenant.ListMembersByIdAccountRequest
	24, // 30: erposfnb.tenant.TenantService.AddMember:input_type -> erposfnb.tenant.AddMemberRequest
	26, // 31: erposfnb.tenant.TenantService.UpdateMember:input_type -> erposfnb.tenant.UpdateMemberRequest
	28, // 32: erposfnb.tenant.TenantService.RemoveMember:input_type -> erposfnb.tenant.RemoveMemberRequest
	30, // 33: erposfnb.tenant.TenantService.Summarize:input_type -> erposfnb.tenant.SummarizeRequest
	32, // 34: erposfnb.tenant.TenantService.CheckBanned:input_type -> erposfnb.tenant.CheckBannedRequest
	5,  // 35: erposfnb.tenant.TenantService.CreateTenant:output_type -> erposfnb.tenant.CreateTenantResponse
	7,  // 36: erposfnb.tenant.TenantService.ListTenants:output_type -> erposfnb.tenant.ListTenantsResponse
	9,  // 37: erposfnb.tenant.TenantService.GetTenant:output_type -> erposfnb.tenant.GetTenantResponse
	11, // 38: erposfnb.tenant.TenantService.UpdateTenant:output_type -> erposfnb.tenant.UpdateTenantResponse
	13, // 39: erposfnb.tenant.TenantService.CreateBranch:output_type -> erposfnb.tenant.CreateBranchResponse
	15, // 40: erposfnb.tenant.TenantService.ListBranches:output_type -> erposfnb.tenant.ListBranchesResponse
	17, // 41: erposfnb.tenant.TenantService.GetBranch:output_type -> erposfnb.tenant.GetBranchResponse
	19, // 42: erposfnb.tenant.TenantService.UpdateBranch:output_type -> erposfnb.tenant.UpdateBranchResponse
	21, // 43: erposfnb.tenant.TenantService.ListMembers:output_type -> erposfnb.tenant.ListMembersResponse
	23, // 44: erposfnb.tenant.TenantService.ListMembersByIdAccount:output_type -> erposfnb.tenant.ListMembersByIdAccountResponse
	25, // 45: erposfnb.tenant.TenantService.AddMember:output_type -> erposfnb.tenant.AddMemberResponse
	27, // 46: erposfnb.tenant.TenantService.UpdateMember:output_type -> erposfnb.tenant.UpdateMemberResponse
	29, // 47: erposfnb.tenant.TenantService.RemoveMember:output_type -> erposfnb.tenant.RemoveMemberResponse
	31, // 48: erposfnb.tenant.TenantService.Summarize:output_type -> erposfnb.tenant.SummarizeResponse
	33, // 49: erposfnb.tenant.TenantService.CheckBanned:output_type -> erposfnb.tenant.CheckBannedResponse
	35, // [35:50] is the sub-list for method output_type
	20, // [20:35] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_tenant_tenant_proto_init() }
func file_tenant_tenant_proto_init() {
	if File_tenant_tenant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tenant_tenant_proto_rawDesc), len(file_tenant_tenant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tenant_tenant_proto_goTypes,
		DependencyIndexes: file_tenant_tenant_proto_depIdxs,
		MessageInfos:      file_tenant_tenant_proto_msgTypes,
	}.Build()
	File_tenant_tenant_proto = out.File
	file_tenant_tenant_proto_goTypes = nil
	file_tenant_tenant_proto_depIdxs = nil
}
