// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: common/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Currency is the money unit of a price field.
// Tag 0 is reserved and never carries a real value.
type Currency int32

const (
	Currency_CURRENCY_UNSPECIFIED Currency = 0
	Currency_CURRENCY_USD         Currency = 1
)

// Enum value maps for Currency.
var (
	Currency_name = map[int32]string{
		0: "CURRENCY_UNSPECIFIED",
		1: "CURRENCY_USD",
	}
	Currency_value = map[string]int32{
		"CURRENCY_UNSPECIFIED": 0,
		"CURRENCY_USD":         1,
	}
)

func (x Currency) Enum() *Currency {
	p := new(Currency)
	*p = x
	return p
}

func (x Currency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Currency) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[0].Descriptor()
}

func (Currency) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[0]
}

func (x Currency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Currency.Descriptor instead.
func (Currency) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{0}
}

// MeasureType is the mass and volume unit family.
// Mass converts to mass only, volume converts to volume only.
// The unit list is shared by pos and warehouse stock rows.
type MeasureType int32

const (
	MeasureType_MEASURE_TYPE_UNSPECIFIED MeasureType = 0
	MeasureType_MEASURE_TYPE_TON         MeasureType = 1
	MeasureType_MEASURE_TYPE_KG          MeasureType = 2
	MeasureType_MEASURE_TYPE_G           MeasureType = 3
	MeasureType_MEASURE_TYPE_MG          MeasureType = 4
	MeasureType_MEASURE_TYPE_L           MeasureType = 5
	MeasureType_MEASURE_TYPE_ML          MeasureType = 6
)

// Enum value maps for MeasureType.
var (
	MeasureType_name = map[int32]string{
		0: "MEASURE_TYPE_UNSPECIFIED",
		1: "MEASURE_TYPE_TON",
		2: "MEASURE_TYPE_KG",
		3: "MEASURE_TYPE_G",
		4: "MEASURE_TYPE_MG",
		5: "MEASURE_TYPE_L",
		6: "MEASURE_TYPE_ML",
	}
	MeasureType_value = map[string]int32{
		"MEASURE_TYPE_UNSPECIFIED": 0,
		"MEASURE_TYPE_TON":         1,
		"MEASURE_TYPE_KG":          2,
		"MEASURE_TYPE_G":           3,
		"MEASURE_TYPE_MG":          4,
		"MEASURE_TYPE_L":           5,
		"MEASURE_TYPE_ML":          6,
	}
)

func (x MeasureType) Enum() *MeasureType {
	p := new(MeasureType)
	*p = x
	return p
}

func (x MeasureType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MeasureType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[1].Descriptor()
}

func (MeasureType) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[1]
}

func (x MeasureType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MeasureType.Descriptor instead.
func (MeasureType) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{1}
}

// LengthType is the length unit family for a box dimension.
type LengthType int32

const (
	LengthType_LENGTH_TYPE_UNSPECIFIED LengthType = 0
	LengthType_LENGTH_TYPE_MM          LengthType = 1
	LengthType_LENGTH_TYPE_CM          LengthType = 2
	LengthType_LENGTH_TYPE_M           LengthType = 3
	LengthType_LENGTH_TYPE_KM          LengthType = 4
)

// Enum value maps for LengthType.
var (
	LengthType_name = map[int32]string{
		0: "LENGTH_TYPE_UNSPECIFIED",
		1: "LENGTH_TYPE_MM",
		2: "LENGTH_TYPE_CM",
		3: "LENGTH_TYPE_M",
		4: "LENGTH_TYPE_KM",
	}
	LengthType_value = map[string]int32{
		"LENGTH_TYPE_UNSPECIFIED": 0,
		"LENGTH_TYPE_MM":          1,
		"LENGTH_TYPE_CM":          2,
		"LENGTH_TYPE_M":           3,
		"LENGTH_TYPE_KM":          4,
	}
)

func (x LengthType) Enum() *LengthType {
	p := new(LengthType)
	*p = x
	return p
}

func (x LengthType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LengthType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[2].Descriptor()
}

func (LengthType) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[2]
}

func (x LengthType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LengthType.Descriptor instead.
func (LengthType) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{2}
}

// RoleAccess is the role a member holds in a tenant branch.
// Gateway forwards the value to tenant without a rewrite.
type RoleAccess int32

const (
	RoleAccess_ROLE_ACCESS_UNSPECIFIED RoleAccess = 0
	RoleAccess_ROLE_ACCESS_NONE        RoleAccess = 1
	RoleAccess_ROLE_ACCESS_POS         RoleAccess = 2
	RoleAccess_ROLE_ACCESS_ERP         RoleAccess = 3
	RoleAccess_ROLE_ACCESS_WAREHOUSE   RoleAccess = 4
)

// Enum value maps for RoleAccess.
var (
	RoleAccess_name = map[int32]string{
		0: "ROLE_ACCESS_UNSPECIFIED",
		1: "ROLE_ACCESS_NONE",
		2: "ROLE_ACCESS_POS",
		3: "ROLE_ACCESS_ERP",
		4: "ROLE_ACCESS_WAREHOUSE",
	}
	RoleAccess_value = map[string]int32{
		"ROLE_ACCESS_UNSPECIFIED": 0,
		"ROLE_ACCESS_NONE":        1,
		"ROLE_ACCESS_POS":         2,
		"ROLE_ACCESS_ERP":         3,
		"ROLE_ACCESS_WAREHOUSE":   4,
	}
)

func (x RoleAccess) Enum() *RoleAccess {
	p := new(RoleAccess)
	*p = x
	return p
}

func (x RoleAccess) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoleAccess) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[3].Descriptor()
}

func (RoleAccess) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[3]
}

func (x RoleAccess) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoleAccess.Descriptor instead.
func (RoleAccess) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{3}
}

// StockRequestStatus is the shared pos to warehouse request lifecycle.
// The pos DB enum is a subset and has no rejected value.
// The warehouse DB enum holds every value.
type StockRequestStatus int32

const (
	StockRequestStatus_STOCK_REQUEST_STATUS_UNSPECIFIED StockRequestStatus = 0
	StockRequestStatus_STOCK_REQUEST_STATUS_PENDING     StockRequestStatus = 1
	StockRequestStatus_STOCK_REQUEST_STATUS_APPROVED    StockRequestStatus = 2
	StockRequestStatus_STOCK_REQUEST_STATUS_REJECTED    StockRequestStatus = 3
	StockRequestStatus_STOCK_REQUEST_STATUS_SHIPPED     StockRequestStatus = 4
	StockRequestStatus_STOCK_REQUEST_STATUS_RECEIVED    StockRequestStatus = 5
)

// Enum value maps for StockRequestStatus.
var (
	StockRequestStatus_name = map[int32]string{
		0: "STOCK_REQUEST_STATUS_UNSPECIFIED",
		1: "STOCK_REQUEST_STATUS_PENDING",
		2: "STOCK_REQUEST_STATUS_APPROVED",
		3: "STOCK_REQUEST_STATUS_REJECTED",
		4: "STOCK_REQUEST_STATUS_SHIPPED",
		5: "STOCK_REQUEST_STATUS_RECEIVED",
	}
	StockRequestStatus_value = map[string]int32{
		"STOCK_REQUEST_STATUS_UNSPECIFIED": 0,
		"STOCK_REQUEST_STATUS_PENDING":     1,
		"STOCK_REQUEST_STATUS_APPROVED":    2,
		"STOCK_REQUEST_STATUS_REJECTED":    3,
		"STOCK_REQUEST_STATUS_SHIPPED":     4,
		"STOCK_REQUEST_STATUS_RECEIVED":    5,
	}
)

func (x StockRequestStatus) Enum() *StockRequestStatus {
	p := new(StockRequestStatus)
	*p = x
	return p
}

func (x StockRequestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StockRequestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[4].Descriptor()
}

func (StockRequestStatus) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[4]
}

func (x StockRequestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StockRequestStatus.Descriptor instead.
func (StockRequestStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{4}
}

var File_common_common_proto protoreflect.FileDescriptor

const file_common_common_proto_rawDesc = "" +
	"\n" +
	"\x13common/common.proto\x12\x0ferposfnb.common*6\n" +
	"\bCurrency\x12\x18\n" +
	"\x14CURRENCY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fCURRENCY_USD\x10\x01*\xa8\x01\n" +
	"\vMeasureType\x12\x1c\n" +
	"\x18MEASURE_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10MEASURE_TYPE_TON\x10\x01\x12\x13\n" +
	"\x0fMEASURE_TYPE_KG\x10\x02\x12\x12\n" +
	"\x0eMEASURE_TYPE_G\x10\x03\x12\x13\n" +
	"\x0fMEASURE_TYPE_MG\x10\x04\x12\x12\n" +
	"\x0eMEASURE_TYPE_L\x10\x05\x12\x13\n" +
	"\x0fMEASURE_TYPE_ML\x10\x06*x\n" +
	"\n" +
	"LengthType\x12\x1b\n" +
	"\x17LENGTH_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eLENGTH_TYPE_MM\x10\x01\x12\x12\n" +
	"\x0eLENGTH_TYPE_CM\x10\x02\x12\x11\n" +
	"\rLENGTH_TYPE_M\x10\x03\x12\x12\n" +
	"\x0eLENGTH_TYPE_KM\x10\x04*\x84\x01\n" +
	"\n" +
	"RoleAccess\x12\x1b\n" +
	"\x17ROLE_ACCESS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ROLE_ACCESS_NONE\x10\x01\x12\x13\n" +
	"\x0fROLE_ACCESS_POS\x10\x02\x12\x13\n" +
	"\x0fROLE_ACCESS_ERP\x10\x03\x12\x19\n" +
	"\x15ROLE_ACCESS_WAREHOUSE\x10\x04*\xe7\x01\n" +
	"\x12StockRequestStatus\x12$\n" +
	" STOCK_REQUEST_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cSTOCK_REQUEST_STATUS_PENDING\x10\x01\x12!\n" +
	"\x1dSTOCK_REQUEST_STATUS_APPROVED\x10\x02\x12!\n" +
	"\x1dSTOCK_REQUEST_STATUS_REJECTED\x10\x03\x12 \n" +
	"\x1cSTOCK_REQUEST_STATUS_SHIPPED\x10\x04\x12!\n" +
	"\x1dSTOCK_REQUEST_STATUS_RECEIVED\x10\x05B/Z-github.com/prothegee/erposfnb-protobuf/commonb\x06proto3"

var (
	file_common_common_proto_rawDescOnce sync.Once
	file_common_common_proto_rawDescData []byte
)

func file_common_common_proto_rawDescGZIP() []byte {
	file_common_common_proto_rawDescOnce.Do(func() {
		file_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_common_proto_rawDesc), len(file_common_common_proto_rawDesc)))
	})
	return file_common_common_proto_rawDescData
}

var file_common_common_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_common_common_proto_goTypes = []any{
	(Currency)(0),           // 0: erposfnb.common.Currency
	(MeasureType)(0),        // 1: erposfnb.common.MeasureType
	(LengthType)(0),         // 2: erposfnb.common.LengthType
	(RoleAccess)(0),         // 3: erposfnb.common.RoleAccess
	(StockRequestStatus)(0), // 4: erposfnb.common.StockRequestStatus
}
var file_common_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_common_proto_init() }
func file_common_common_proto_init() {
	if File_common_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_common_proto_rawDesc), len(file_common_common_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_common_proto_goTypes,
		DependencyIndexes: file_common_common_proto_depIdxs,
		EnumInfos:         file_common_common_proto_enumTypes,
	}.Build()
	File_common_common_proto = out.File
	file_common_common_proto_goTypes = nil
	file_common_common_proto_depIdxs = nil
}
